In [2]:
import pandas as pd
import numpy as np

In [3]:
# Read the CSV file into a DataFrame
df = pd.read_csv("spam.csv")
print(df.head())

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...


In [4]:
# Create a new column 'spam' based on the 'Category' column
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
print(df.head())


  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0


In [5]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['Message'], df['spam'], test_size=0.25)
X_train, X_test, y_train, y_test

(4638    Oh ho. Is this the first time u use these type...
 3072       Apart from the one i told you about yesterday?
 3652         Want to send me a virtual hug?... I need one
 2657                    Feel like trying kadeem again? :V
 2268                                    Finish liao... U?
                               ...                        
 1616                         Mm i had my food da from out
 5283                      Yeah, probably here for a while
 2689    Yes I know the cheesy songs from frosty the sn...
 1985    Urgent! Please call 09061743810 from landline....
 2622    Lol! Nah wasn't too bad thanks. Its good to b ...
 Name: Message, Length: 4179, dtype: object,
 1571    No:-)i got rumour that you going to buy apartm...
 2376    Thanx 4 2day! U r a goodmate I THINK UR RITE S...
 4602    FreeMsg: Txt: CALL to No: 86888 & claim your r...
 5161    Lol no. I just need to cash in my nitros. Hurr...
 209     You please give us connection today itself bef...
           

In [6]:
# Convert text data into a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_Count = v.fit_transform(X_train.values)
print(X_train_Count.toarray()[:3])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
# Train a Naive Bayes classifier
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_Count, y_train)


MultinomialNB()

In [8]:
# Example predictions
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20 percent discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
print(model.predict(emails_count))


[0 1]


In [9]:
# Measure accuracy of the model
X_test_Count = v.transform(X_test)
print(model.score(X_test_Count, y_test))


0.9849246231155779
